name: tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  pwsh:
    name: Pester (pwsh 7)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Pester
        shell: pwsh
        run: |
          Install-Module Pester -MinimumVersion 5.5.0 -Force -SkipPublisherCheck -Scope CurrentUser
          Import-Module Pester -MinimumVersion 5.0 -Force
          $c = New-PesterConfiguration
          $c.Run.Path = './tests'
          $c.Run.Exit = $true
          $c.Output.Verbosity = 'Detailed'
          Invoke-Pester -Configuration $c

  windows-powershell:
    name: Pester (Windows PowerShell 5.1)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Pester
        shell: powershell
        run: |
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module Pester -MinimumVersion 5.5.0 -Force -SkipPublisherCheck -Scope CurrentUser
          Import-Module Pester -MinimumVersion 5.0 -Force
          $c = New-PesterConfiguration
          $c.Run.Path = './tests'
          $c.Run.Exit = $true
          $c.Output.Verbosity = 'Detailed'
          Invoke-Pester -Configuration $c
